#!/bin/sh
### BEGIN INIT INFO
# Provides:          S01beepykbd
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Loads Beepy keyboard keymap
### END INIT INFO

umask 077

start() {
	/usr/bin/loadkeys /usr/local/share/kbd/keymapsbeepy-kbd.map
	# System clock has to be set from hwclock after udev is loaded
	echo "OK"
}
stop() {
	TZ=$(cat /boot/timezone.txt) /sbin/hwclock -l --systohc
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
