#!/bin/sh
#
# beepykbd        Loads Beepy keyboard keymap.
#

umask 077

start() {
	/usr/bin/loadkeys /usr/share/keymaps/beepy-kbd.map
	# System clock has to be set from hwclock after udev is loaded
	echo "OK"
}
stop() {
	TZ=$(cat /boot/timezone.txt) /sbin/hwclock -l --systohc
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
